- name: Instalar entorno gráfico Qt 5.15
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'
          extra: '--no-updates'
